language: go

go:
  - 1.7.1

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -y
  - sudo apt-get install glide

script:
  - make test

sudo: false
